# Generated by Django 4.2.2 on 2023-11-12 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=2000, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='images/', verbose_name='picture')),
                ('filename', models.CharField(max_length=2000, null=True, verbose_name='filename')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references', models.CharField(max_length=300, null=True, verbose_name='references')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='width')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='length')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='height')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='ads.category')),
            ],
            options={
                'verbose_name': 'piece',
                'verbose_name_plural': 'pieces',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=300, null=True, verbose_name='model')),
                ('registration_number', models.CharField(max_length=300, null=True, validators=[django.core.validators.RegexValidator('[A-HJ-NP-TV-Z]{2}[\\s-]{0,1}[0-9]{3}[\\s-]{0,1}[A-HJ-NP-TV-Z]{2}|[0-9]{2,4}[\\s-]{0,1}[A-Z]{1,3}[\\s-]{0,1}[0-9]{2}', 'Your string should contain letter A in it.')], verbose_name='registration_number')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='year')),
                ('type', models.CharField(choices=[('CTD', 'citadine'), ('BLN', 'berline'), ('SUV', 'suv'), ('4x4', '4*4')], max_length=200, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='ads.brand')),
                ('pieces', models.ManyToManyField(through='ads.Ad', to='ads.piece')),
            ],
            options={
                'verbose_name': 'vehiclemodel',
                'verbose_name_plural': 'vehiclemodels',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.CharField(max_length=2000, null=True, verbose_name='matter')),
                ('colors', models.ManyToManyField(to='ads.color')),
            ],
            options={
                'verbose_name': 'matter',
                'verbose_name_plural': 'matters',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.piece'),
        ),
        migrations.AddField(
            model_name='ad',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.vehiclemodel'),
        ),
    ]
