# Generated by Django 4.2.2 on 2023-11-12 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='pieces',
            field=models.ManyToManyField(blank=True, null=True, through='ads.Ad', to='ads.piece'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='registration_number',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator('[A-HJ-NP-TV-Z]{2}[\\s-]{0,1}[0-9]{3}[\\s-]{0,1}[A-HJ-NP-TV-Z]{2}|[0-9]{2,4}[\\s-]{0,1}[A-Z]{1,3}[\\s-]{0,1}[0-9]{2}', 'Your string should contain letter A in it.')], verbose_name='registration_number'),
        ),
    ]
