# Generated by Django 4.2.2 on 2023-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_vehiclemodel_pieces_piece_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='filename',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
