# Generated by Django 4.2.2 on 2023-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_vehiclemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='type',
            field=models.CharField(choices=[('CTD', 'Citadine'), ('BLN', 'Berline'), ('SUV', 'SUV'), ('4x4', '4*4'), ('PKP', 'Pick-up'), ('VE', 'VE'), ('VH', 'VH')], max_length=200, null=True),
        ),
    ]
