# Generated by Django 4.2.2 on 2023-11-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_brand_brand_type_alter_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='filename',
        ),
        migrations.AddField(
            model_name='picture',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.ad', verbose_name='images'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='picture',
            table='picture',
        ),
    ]
