# Generated by Django 4.2.2 on 2023-11-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_picture_filename_picture_ad_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='picture',
            table=None,
        ),
    ]
