# Generated by Django 4.2.2 on 2023-11-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_picture_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='description',
            new_name='filename',
        ),
    ]
